
/**
 * Store Actions
 */
export const STORE_FETCH_REQUEST = 'STORE_FETCH_REQUEST';
export const STORE_FETCH_SUCCESS = 'STORE_FETCH_SUCCESS';
export const STORE_FETCH_FAILURE = 'STORE_FETCH_FAILURE';

export const SET_FILTER_PARAMS = 'SET_FILTER_PARAMS';
export const SET_FILTER_PARAMS_CUSTOM_LIST = 'SET_FILTER_PARAMS_CUSTOM_LIST';
export const SET_FILTER_PARAMS_PROMOTION = 'SET_FILTER_PARAMS_PROMOTION';
export const SET_FILTER_CATEGORY_PRODUCTS = 'SET_FILTER_CATEGORY_PRODUCTS';
export const SET_FILTER_PRODUCT_VARIATION = 'SET_FILTER_PRODUCT_VARIATION';

export const SHOPWINDOW_FETCH_REQUEST = 'SHOPWINDOW_FETCH_REQUEST';
export const SHOPWINDOW_FETCH_SUCCESS = 'SHOPWINDOW_FETCH_SUCCESS';
export const SHOPWINDOW_FETCH_FAILURE = 'SHOPWINDOW_FETCH_FAILURE';

export const CURRENT_PRODUCT_FETCH_REQUEST = 'CURRENT_PRODUCT_FETCH_REQUEST';
export const CURRENT_PRODUCT_FETCH_SUCCESS = 'CURRENT_PRODUCT_FETCH_SUCCESS';
export const CURRENT_PRODUCT_FETCH_FAILURE = 'CURRENT_PRODUCT_FETCH_FAILURE';

export const CURRENT_PRODUCT_WIPE = 'CURRENT_PRODUCT_WIPE';

export const SET_VISIT_REQUEST = 'SET_VISIT_REQUEST';
export const SET_VISIT_SUCCESS = 'SET_VISIT_SUCCESS';
export const SET_VISIT_FAILURE = 'SET_VISIT_FAILURE';

export const USER_CUSTOMER_REQUEST = 'USER_CUSTOMER_REQUEST';
export const USER_CUSTOMER_SUCCESS = 'USER_CUSTOMER_SUCCESS';
export const USER_CUSTOMER_FAILURE = 'USER_CUSTOMER_FAILURE';

/**
 * Auth Actions
 */
export const USER_AUTHENTICATE_REQUEST = 'USER_AUTHENTICATE_REQUEST';
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS';
export const USER_AUTHENTICATE_FAILURE = 'USER_AUTHENTICATE_FAILURE';

export const USER_FB_CONNECT_REQUEST = 'USER_FB_CONNECT_REQUEST';
export const USER_FB_CONNECT_SUCCESS = 'USER_FB_CONNECT_SUCCESS';
export const USER_FB_CONNECT_FAILURE = 'USER_FB_CONNECT_FAILURE';

export const USER_RECOVER_PASSWORD_REQUEST = 'USER_RECOVER_PASSWORD_REQUEST';
export const USER_RECOVER_PASSWORD_SUCCESS = 'USER_RECOVER_PASSWORD_SUCCESS';
export const USER_RECOVER_PASSWORD_FAILURE = 'USER_RECOVER_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';

// remove facebookData da store para evitar redirect
// no form de login
export const CLEAR_LOGIN_ATTEMPT = 'CLEAR_LOGIN_ATTEMPT';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAILURE = 'CREATE_CART_FAILURE';

/**
 * Cart Actions
 */
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const RESET_ORDER_STATE = 'RESET_ORDER_STATE';

export const REMOVE_TO_CART_REQUEST = 'REMOVE_TO_CART_REQUEST';
export const REMOVE_TO_CART_SUCCESS = 'REMOVE_TO_CART_SUCCESS';
export const REMOVE_TO_CART_FAILURE = 'REMOVE_TO_CART_FAILURE';

export const UPDATE_QTD_PRODUCT_CART_REQUEST = 'UPDATE_QTD_PRODUCT_CART_REQUEST';
export const UPDATE_QTD_PRODUCT_CART_SUCCESS = 'UPDATE_QTD_PRODUCT_CART_SUCCESS';
export const UPDATE_QTD_PRODUCT_CART_FAILURE = 'UPDATE_QTD_PRODUCT_CART_FAILURE';

export const REMOVE_CART = 'REMOVE_CART';

/**
 * Payment Actions
 */
export const FETCH_PAYMENT_OPTIONS_REQUEST = 'FETCH_PAYMENT_OPTIONS_REQUEST';
export const FETCH_PAYMENT_OPTIONS_SUCCESS = 'FETCH_PAYMENT_OPTIONS_SUCCESS';
export const FETCH_PAYMENT_OPTIONS_FAILURE = 'FETCH_PAYMENT_OPTIONS_FAILURE';

export const MAKE_PAYMENT_REQUEST = 'MAKE_PAYMENT_REQUEST';
export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const MAKE_PAYMENT_FAILURE = 'MAKE_PAYMENT_FAILURE';

export const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST';
export const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS';
export const MY_ORDER_FAILURE = 'MY_ORDER_FAILURE';

export const REMAKE_PAYMENT_ORDER_REQUEST = 'REMAKE_PAYMENT_ORDER_REQUEST';
export const REMAKE_PAYMENT_ORDER_SUCCESS = 'REMAKE_PAYMENT_ORDER_SUCCESS';
export const REMAKE_PAYMENT_ORDER_FAILURE = 'REMAKE_PAYMENT_ORDER_FAILURE';

export const RESET_REMAKE_PAYMENT_ORDER_STATE = 'RESET_REMAKE_PAYMENT_ORDER_STATE';

/**
 * Campaings
 */
export const FETCH_CAMPAIGN_REQUEST = 'FETCH_CAMPAIGN_REQUEST';
export const FETCH_CAMPAIGN_SUCCESS = 'FETCH_CAMPAIGN_SUCCESS';
export const FETCH_CAMPAIGN_FAILURE = 'FETCH_CAMPAIGN_FAILURE';

export const FETCH_CAMPAIGNS_REQUEST = 'FETCH_CAMPAIGNS_REQUEST';
export const FETCH_CAMPAIGNS_SUCCESS = 'FETCH_CAMPAIGNS_SUCCESS';
export const FETCH_CAMPAIGNS_FAILURE = 'FETCH_CAMPAIGNS_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_BRANDS_REQUEST = 'FETCH_BRANDS_REQUEST';
export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';
export const FETCH_BRANDS_FAILURE = 'FETCH_BRANDS_FAILURE';

export const FETCH_METHOD_DELIVERY_PRODUCT_REQUEST = 'FETCH_METHOD_DELIVERY_PRODUCT_REQUEST';
export const FETCH_METHOD_DELIVERY_PRODUCT_SUCCESS = 'FETCH_METHOD_DELIVERY_PRODUCT_SUCCESS';
export const FETCH_METHOD_DELIVERY_PRODUCT_FAILURE = 'FETCH_METHOD_DELIVERY_PRODUCT_FAILURE';

export const FETCH_METHOD_DELIVERY_CART_REQUEST = 'FETCH_METHOD_DELIVERY_CART_REQUEST';
export const FETCH_METHOD_DELIVERY_CART_SUCCESS = 'FETCH_METHOD_DELIVERY_CART_SUCCESS';
export const FETCH_METHOD_DELIVERY_CART_FAILURE = 'FETCH_METHOD_DELIVERY_CART_FAILURE';

export const FETCH_ADDRESS_SAVE_REQUEST = 'FETCH_ADDRESS_SAVE_REQUES';
export const FETCH_ADDRESS_SAVE_SUCCESS = 'FETCH_ADDRESS_SAVE_SUCCES';
export const FETCH_ADDRESS_SAVE_FAILURE = 'FETCH_ADDRESS_SAVE_FAILUR';
/**
 * Show / hide search filters
 */
export const TOGGLE_SEARCH_FILTER = 'TOGGLE_SEARCH_FILTER';

/**
 * When visulize product
 */
export const TO_PRODUCT_VIEW = 'TO_PRODUCT_VIEW';

export const PROMOTION_FETCH_REQUEST = 'PROMOTION_FETCH_REQUEST';
export const PROMOTION_FETCH_SUCCESS = 'PROMOTION_FETCH_SUCCESS';
export const PROMOTION_FETCH_FAILURE = 'PROMOTION_FETCH_FAILURE';

export const FETCH_CUSTOM_LIST_REQUEST = 'FETCH_CUSTOM_LIST_REQUEST';
export const FETCH_CUSTOM_LIST_SUCCESS = 'FETCH_CUSTOM_LIST_SUCCESS';
export const FETCH_CUSTOM_LIST_FAILURE = 'FETCH_CUSTOM_LIST_FAILURE';

export const FETCH_CATEGORY_PRODUCTS_REQUEST = 'FETCH_CATEGORY_PRODUCTS_REQUES';
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = 'FETCH_CATEGORY_PRODUCTS_SUCCES';
export const FETCH_CATEGORY_PRODUCTS_FAILURE = 'FETCH_CATEGORY_PRODUCTS_FAILUR';

export const SET_FILTER_BRANDS_PRODUCTS = 'SET_FILTER_BRANDS_PRODUCTS';
export const FETCH_BRANDS_PRODUCTS_REQUEST = 'FETCH_BRANDS_PRODUCTS_REQUEST';
export const FETCH_BRANDS_PRODUCTS_SUCCESS = 'FETCH_BRANDS_PRODUCTS_SUCCESS';
export const FETCH_BRANDS_PRODUCTS_FAILURE = 'FETCH_BRANDS_PRODUCTS_FAILURE';

/*
 * CEP
 * Preenchimento de endereço baseado no CEP
 */

export const FETCH_API_CEP_REQUEST = 'FETCH_API_CEP_REQUEST';
export const FETCH_API_CEP_SUCCESS = 'FETCH_API_CEP_SUCCESS';
export const FETCH_API_CEP_FAILURE = 'FETCH_API_CEP_FAILURE';

export const USER_CREATE_NEW_PASSWORD_REQUEST = 'USER_CREATE_NEW_PASSWORD_REQUEST';
export const USER_CREATE_NEW_PASSWORD_SUCCESS = 'USER_CREATE_NEW_PASSWORD_SUCCESS';
export const USER_CREATE_NEW_PASSWORD_FAILURE = 'USER_CREATE_NEW_PASSWORD_FAILURE';

